### ISSUE TITLE
Change 'Run program' shortcut to Shift-Enter

### ISSUE THREAD

**Issue by mehlon** [oden-lang/playground#11]
A minor issue, I think it'd be nice if the 'Run program' shortcut were Shift-Enter, like on the Go playground.

**Comment by owickstrom** [comment]
Sounds good. Would you like to add that as a shortcut as well, and keep **CTRL-R**?

**Comment by mehlon** [comment]
I'd rather just have shift-enter. Ctrl-R already means refresh on Windows.

**Comment by owickstrom** [comment]
That's true, it actually clashed on Windows if I remember correctly. OK, we'll go with only Shift-Enter.
